### ISSUE TITLE
Using this in React Typescript

### ISSUE THREAD

**Issue by forcmti** [joemaddalone/react-svg-path#93]
While using this library in react typescript, i was not able to import any of the modules.
I am getting the error:

`Could not find a declaration file for module 'react-svg-path'.
node_modules/react-svg-path/dist/index.cjs.js' implicitly has an 'any' type.`
` Try npm i --save-dev @types/react-svg-path if it exists or add a new declaration (.d.ts) file containing declare module 'react-svg-path
`

Is there any other method to install this or do i have to exclude this module from tsconfig file?

**Comment by joemaddalone** [comment]
There is no declaration file for this project at the moment.
You have a few options.
```
// @ts-ignore
import { Svg, Circle } from 'react-svg-path';
```

in your `tsconfig.json` you could add
```
"noImplicitAny": false
```

Or as you mentioned you can try to exclude the module in your `tsconfig` as well.

**Comment by forcmti** [comment]
Ok, thanks for the information
